Call SR1.Instrument.CloseForm(10)
FormID = SR1.QuickMeas.FreqResp.OpenFormwID()
FormID = SR1.QuickMeas.OpenFormwID()
Call SR1.QuickMeas.Setup()
Call SR1.Instrument.CloseForm(5)
SR1.QuickMeas.FreqResp.LevelSteps = 199
Call SR1.QuickMeas.FreqResp.Sweep()
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(101))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_0.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(102))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_1.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(103))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_2.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(104))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_3.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(105))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_4.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(106))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_5.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(107))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_6.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(108))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_7.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(109))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_8.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(110))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_9.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(111))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_10.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(112))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_11.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(113))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_12.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(114))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_13.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(115))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_14.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(116))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_15.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(117))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_16.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(118))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_17.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(119))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_18.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(120))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_19.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(121))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_20.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(122))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_21.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(123))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_22.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(124))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_23.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(125))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_24.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(126))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_25.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(127))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_26.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(128))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_27.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(129))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_28.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(130))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_29.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(131))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_30.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(132))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_31.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(133))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_32.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(134))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_33.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(135))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_34.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(136))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_35.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(137))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_36.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(138))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_37.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(139))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_38.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(140))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_39.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(141))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_40.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(142))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_41.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(143))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_42.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(144))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_43.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(145))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_44.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(146))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_45.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(147))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_46.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(148))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_47.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(149))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_48.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(150))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_49.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(151))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_50.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(152))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_51.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(153))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_52.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(154))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_53.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(155))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_54.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(156))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_55.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(157))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_56.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(158))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_57.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(159))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_58.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(160))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_59.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(161))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_60.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(162))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_61.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(163))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_62.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(164))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_63.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(165))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_64.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(166))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_65.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(167))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_66.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(168))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_67.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(169))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_68.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(170))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_69.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(171))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_70.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(172))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_71.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(173))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_72.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(174))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_73.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(175))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_74.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(176))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_75.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(177))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_76.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(178))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_77.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(179))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_78.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(180))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_79.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(181))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_80.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(182))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_81.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(183))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_82.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(184))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_83.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(185))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_84.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(186))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_85.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(187))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_86.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(188))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_87.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(189))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_88.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(190))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_89.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(191))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_90.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(192))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_91.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(193))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_92.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(194))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_93.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(195))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_94.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(196))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_95.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(197))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_96.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(198))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_97.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(199))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_98.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(200))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_99.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(201))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_100.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(202))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_101.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(203))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_102.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(204))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_103.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(205))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_104.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(206))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_105.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(207))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_106.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(208))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_107.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(209))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_108.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(210))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_109.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(211))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_110.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(212))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_111.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(213))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_112.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(214))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_113.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(215))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_114.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(216))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_115.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(217))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_116.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(218))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_117.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(219))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_118.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(220))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_119.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(221))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_120.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(222))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_121.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(223))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_122.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(224))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_123.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(225))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_124.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(226))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_125.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(227))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_126.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(228))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_127.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(229))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_128.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(230))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_129.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(231))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_130.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(232))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_131.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(233))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_132.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(234))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_133.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(235))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_134.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(236))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_135.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(237))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_136.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(238))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_137.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(239))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_138.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(240))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_139.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(241))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_140.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(242))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_141.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(243))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_142.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(244))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_143.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(245))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_144.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(246))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_145.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(247))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_146.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(248))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_147.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(249))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_148.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(250))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_149.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(251))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_150.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(252))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_151.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(253))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_152.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(254))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_153.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(255))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_154.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(256))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_155.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(257))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_156.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(258))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_157.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(259))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_158.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(260))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_159.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(261))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_160.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(262))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_161.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(263))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_162.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(264))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_163.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(265))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_164.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(266))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_165.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(267))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_166.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(268))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_167.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(269))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_168.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(270))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_169.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(271))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_170.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(272))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_171.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(273))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_172.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(274))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_173.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(275))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_174.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(276))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_175.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(277))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_176.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(278))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_177.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(279))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_178.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(280))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_179.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(281))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_180.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(282))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_181.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(283))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_182.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(284))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_183.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(285))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_184.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(286))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_185.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(287))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_186.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(288))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_187.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(289))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_188.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(290))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_189.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(291))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_190.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(292))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_191.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(293))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_192.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(294))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_193.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(295))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_194.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(296))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_195.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(297))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_196.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(298))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_197.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(299))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_198.TXT")
Call SR1.Displays.Graph(2).SelectTrace(SR1.Displays.Graph(2).Trace(300))
Call SR1.Displays.Graph(2).ExportData("C:\Documents and Settings\SR1\My Documents\sweep_199.TXT")
Call SR1.Displays.Graph(2).Close()
Call SR1.Instrument.CloseForm(2)